### ISSUE TITLE
Add Java 11 to CI

### ISSUE THREAD

**Issue by dwijnand** [typesafehub/activator-play-tls-example#74]
One way of doing this is by adding the following to `.travis.yml`:

```yaml
matrix:
  include:
    - scala: 2.12.7
      jdk: openjdk11
  allow_failures:
    # Java 11 is still not fully supported. It is good that we are already
    # testing our sample applications to better discover possible problems
    # but we can allow failures here too.
    - jdk: openjdk11
```

Make sure that's the right Scala version.  Also we might want to use AdoptOpenJDK 11 instead of Oracle OpenJDK 11.
